version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null 
  - ps: nuget update -Self
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/NLog.Targets.Seq.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: aDvvick26/4UYAO2vAXGmwAOckdKw16bb2od4vmWzIe4PCncszOWaHt0BurMzfOo
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /NLog.Targets.Seq.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
