resources:
  repositories:
  - repository: self
    type: git
    ref: cigaw
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
    #vmImage: 'windows-latest'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.408'
      
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk '
    inputs:
      useGlobalJson: true

  - task: NuGetToolInstaller@1
    displayName: Use NuGet 6.0.0
    inputs:
      versionSpec: 6.0.0
      checkLatest: true

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'nlog-targets-seq.sln'
    
  - task: PowerShell@2
    displayName: PowerShell Script
    enabled: False
    inputs:
      filePath: Build.ps1

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: 'src/NLog.Targets.Seq/NLog.Targets.Seq.csproj'
      includesymbols: true
      includesource: true
      versioningScheme: 'off'
      nobuild: false
      buildProperties: '--version-suffix=local'


  #- task: DotNetCoreCLI@2
  #  inputs:
  #    command: 'pack'
  #    packagesToPack: 'src/NLog.Targets.Seq/NLog.Targets.Seq.csproj'
  #    includesource: true
  #    versioningScheme: 'off'
  #    buildProperties: --version-suffix=local

  # - task: DotNetCoreCLI@2
  #   displayName: dotnet build
  #   inputs:
  #     searchPatternPack: src/NLog.Targets.Seq/NLog.Targets.Seq.csproj
  #     buildProperties: -o /artifacts --include-source --no-restore
  # - task: CopyFiles@2
  #   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  #   inputs:
  #     SourceFolder: artifacts
  #     TargetFolder: $(Build.ArtifactStagingDirectory)
  #     OverWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
